### PR TITLE
Proposition of new graphics

### PR DESCRIPTION
**Pull request by snouz**
Hi Yousei9/Optera !

I've been working on a number Factorio mod's graphics since January, like warehousing, bioindustries, mferrari's mods, Kira's bob reskins etc...

I've took the time to readjust the graphics of LTN, and I hope you'll find them at your taste (I'm open to modifications of course).

-Mod icon re-imagined
-Depot signal upscaled and "repainted" (from original 32px)
-All signals re-worked to make them more impactful/balanced/clear (# for priority becomes ★, < becomes max, > becomes min, new stack symbol, max train number becomes 2 locomotives)
-Yellow combinator color reinforced

Here's what they look like

<a href="https://imgur.com/wsMUtzF"></a>

<a href="https://imgur.com/FRlJ20J"></a>

This is a proposition only, tell me what you think !

### CODE REVIEW

**Comment by Yousei9** [comment]
- Using the new depot signal for map icons makes a huge difference.
- Hash was used way too often by me, star seems kinda fitting for priority.
- min, max sound like absolute values and not thresholds to me.
- I like changing stack indicator from copper plate to generalized black symbols.
- Adding an off symbol to the alert also works, but looks tacked on with off button being 3d while the alert sign is 2d like in base.
- Technology should be transparent, without LTN branding to be more in line with base iconography.

**Comment by snouz** [comment]
To the point, perfect,
> min, max sound like absolute values and not thresholds to me.
What's the difference for you? I found ≥ / ≤ to be much less striking than min / max. I literally take like 2 seconds to think which is which, and it might be the case for the non-math/non-programming majority. I also searched for other symbols, but they're all less clear than just "min/max". That's up to you
> Adding an off symbol to the alert also works, but looks tacked on with off button being 3d while the alert sign is 2d like in base.
NP reworking that.
> Technology should be transparent, without LTN branding to be more in line with base iconography.
Ah I didn't notice you used that as technology too, I'll make a custom image. Not the first time I see a mod doing that, I should have checked.
> PS: Please add your changes as new layers to the gimp xcf files in .graphics. So i can keep updating icons if necessary.
Erh... I'm using photoshop and I'm much less proficient with gimp. It's all in one file. Do you want me to join the PSD?, or I could also decompose each stuff as transparent pngs? Would you be ok with that?

**Comment by Yousei9** [comment]
> What's the difference for you? I found ≥ / ≤ to be much less striking than min / max. I literally take like 2 seconds to think which is which, and it might be the case for the non-math/non-programming majority. I also searched for other symbols, but they're all less clear than just "min/max". That's up to you

You will not find better symbols "equal to or greater" is ≥ and "equal to or smaller" is ≥.
Non mathematicians may not be familiar with the symbols, but any Factorio player using LTN will also need decider combinators using the same symbols.

> Erh... I'm using photoshop and I'm much less proficient with gimp. It's all in one file. Do you want me to join the PSD?, or I could also decompose each stuff as transparent pngs? Would you be ok with that?

Yes please add the psd to .graphics, Gimp should be able to handle psd files.

**Comment by snouz** [comment]
Please tell me if there's anything I missed.

**Comment by Yousei9** [comment]
I like the better use of space by flipping requester. Probably should use that for the thumbnail as well.

Looking at the thumbnail and tech icon now, I noticed a logical error in my original design.
Stops should be Provider in front and Requester in back to match how we say from A to B.
grafik

I'd prefer a yellow arrow like base logistics tech so it doesn't look too out of place.

PS: Gimp can't properly open gradient arrows. You'd need to compress that layer

**Comment by snouz** [comment]
What do you think now?
<a href="https://imgur.com/C5WkkRI"></a>

<a href="https://imgur.com/K3v1qgx"></a>

**Comment by snouz** [comment]
While I'm at it, do you want me to touch https://mods.factorio.com/mod/VoidChestPlus as well?

**Comment by Yousei9** [comment]
Merged into master.

VCP could do with a fresh coat of paint. The icon design dates back to before I adopted the mod.
I've got two other mods in much more need for updated graphics though:
https://mods.factorio.com/mod/DeepMine
https://mods.factorio.com/mod/Vehicle_Radar

**Comment by Yousei9** [comment]
Gimp didn't import text and background properly either.
I reworked most of it for https://mods.factorio.com/mod/LTN_Content_Reader, couldn't get the small border and 3d effect working though.

**Comment by snouz** [comment]
Let me work on it and I'll do a pull request as well.

**Comment by Yousei9** [comment]
You changed size on low res entity graphics.
Please redo without resizing. Sprite position has to be identical too.

**Comment by snouz** [comment]
Sure. Pushing a pull request right now.
I usually override the native size of LR entities if it's not exactly half, as I use a photoshop script to automatically create a half res version.

**Pull request merged**
