### PR TITLE
A really dirty fix to allow the contents of a train at a depot to be considered the 'empty' state.

### PR DESCRIPTION
**Pull request by Omnifarious**
This is a very quick and dirty change to make this work. But it does work. Basically set bit 30 on the 'this is a depot' signal and the depot requires that the train come back with exactly what it left with.

### CODE REVIEW

**Comment by Yousei9** [comment]
I still don't see what you hope to achieve by this.

Depots always consider trains as empty.

**Comment by Omnifarious** [comment]
You're right. I was incautious with version control and accidentally stomped on your changes. I fixed that.

This doesn't change how LTN works now. It just allows you to create a network in which the concept of what 'empty' means for a train is different. And it causes the train to have to wait at the destination stop until it becomes 'empty'.

So, I will use it to create a network in which an empty train is defined as one with a number of crates sufficient to hold a full train load worth of material. And people who want to use barrels will be able to define an empty train as one with enough empty barrels to fill a train if they were full.

When my 'empty' train reaches a provider stop, it will trade empty crates for full ones. When it reaches a requester stop, it will trade full crates for empty ones. And everything will work.

My main goal for this change was that LTN would (before this change) allow a train to leave a stop when that trade wasn't exactly balanced. And now it doesn't.

**Comment by Yousei9** [comment]
Ah, finally I understand what your goal is.

A scripted solution would be too restrictive and rarely used.
Trains running with empty crates/barrels will have to be put in a network separate from normal empty trains. With barrels this is redundant. If you have dedicated barrel transporting trains you might as well use tankers.

Instead a more practical solution would be to build smart stations:
- LTN by default waits 5s until all loading/unloading stopped, you can abuse that for loading without any change to LTN. If it's too short increase the wait time in mod settings.
- Set loading inserters to only work when unloading ones read a filled crate. That way for each full crate it unloads it will load an empty one.
- It'd be limited to 6 unloading 6loading unless you increase range with bobs inserter or similar.
- All trains used in this manner would still have to be put in their own network as LTN does not check if trains are empty when assigning deliveries.

**Comment by Yousei9** [comment]
I managed to do it without any changes to LTN itself.

[LTN Barrel shipping.zip](https://github.com/Yousei9/Logistic-Train-Network/files/2246548/LTN.Barrel.shipping.zip)

Circuit logic for unloading station where kinda fun to (re)discover.

Top 4 combinators are a white list filter automatically updating to the constant combinator setting requested items.
below that is the normal subtractor for unloading and one diode + signal switch. You have to add each full crate/barrel unloaded here into this one.
below the tracks are a memory cell and inverter for counting the loaded empty barrels

**Comment by Omnifarious** [comment]
Hmmm... I've only set up a circuit network to turn off the inserters as soon as the train has the right number of empty crates in it, and also reduce the stack size to 1 when it gets close to the target. And I still end up being 1 or 2 over every once in awhile. I actually have an insert that takes empties out of one of the cars if it goes over. It might work fine already without the modification I made.

The main reason I had the train stop condition when I wasn't using LTN was that it seemed to greatly reduce the instance of extra boxes sneaking onto the train. But, since LTN has the 'inactivity delay' in there, the '=' condition might not help much anyway.

**Pull request closed without merging**
