### PR TITLE
Separated stop timeout and stop inactivity timeout

### PR DESCRIPTION
**Pull request by TheOddler**
The best of both worlds I hope. This adds a new setting for an inactivity timeout. Similar to the timout but based on inactivity.

I also added the german and chinese translations for the new settings, however these should be dubble checked as they were mostly google translate.

I'll also leave creating a new version number to you ;)

### CODE REVIEW

**Comment by 71e6fd52** [comment]
Maybe I needn't open a new PR?
There are Chinese

```
ltn-dispatcher-stop-timeout=车站超时 (ticks)
ltn-dispatcher-stop-inactivity-timeout=车站无动作超时 (ticks)
```
```
ltn-dispatcher-stop-timeout=强制列车出站所需的时间。\n默认 = 7200（2分钟）
ltn-dispatcher-stop-inactivity-timeout=强制列车出站所需的无动作的时间。\n默认 = 1200（20秒）
```

**Comment by TheOddler** [comment]
Yea, a whole new pullrequest was a bit of overkill probably.

I updated the english descriptions ;)

**Comment by Yousei9** [comment]
Updated chinese translation in dev branch.

**Comment by TheOddler** [comment]
No merge for the other changes? You don't agree both options (normal timeout and inactive timeout) are nice?

**Comment by Yousei9** [comment]
There's no need to have two fail safes.
Time outs should never be triggered in the first place.

**Comment by TheOddler** [comment]
I can take my peace with that. You're right.

**Pull request closed without merging**
