### PR TITLE
Make cleaning invalid stops more robust

### PR DESCRIPTION
**Pull request by jmerdich**
For some reason that may have to do with the "There is my Ghost" mod and/or blueprints in general, I was left with an invalid LTN Stop, and the game crashed on the next request (as the stop was still in the global table and some function looped through and tested every entity for something or other).

This code does a full removal after the existing validity check (instead of just clearing one reference), and makes the removal handle more edge cases.

### CODE REVIEW

**Comment by Yousei9** [comment]
LTN, like any other mod using multiple entities is very picky when some other mod comes along and creates/removes sub entities.
Probably would be more worth while to fix the mod causing this and preventing dozens of other mods having to accommodate for this mod messing with sub entities.

**Comment by jmerdich** [comment]
IMO, it's more the fact that LTN managed to find an invalid entity but only does a partial removal  (then later crashed). I haven't any time into replicating the creation of it, being more focused on fixing my save.

I'll fix the IO entity bug in my code you mentioned sometime this weekend, and will see if I can replicate a glitched stop with vanilla blueprints.

**Comment by Yousei9** [comment]
If you reproduce the crash with logging enabled and post factorio-current.log here i could take a look at it myself.

**Comment by Yousei9** [comment]
I'll consider the lack of response as the issue being resolved.

**Pull request closed without merging**
