### PR TITLE
Provide `ltn-network-id` to partition LTN into multiple networks

### PR DESCRIPTION
**Pull request by mgravell**
This relates to https://github.com/Yousei9/Logistic-Train-Network/issues/14, which is closed "wontfix". I thus know your view on this is that it shouldn't happen, but I simply wanted to lay the code out - am using this locally, and it works great - very pragmatic and simple to configure, and "just works".

Obviously feel free to just close the PR if you still utterly hate the idea, but I thought it might be more compelling if you could see it working without having to do the work that you don't personally need. Otherwise I'll just keep using it locally :)

### CODE REVIEW

**Comment by mgravell** [comment]
disclosure: there's a single edge case here; two *connected* networks where there are depots on both networks with the same name. This could cause a train to end up (after a delivery) at a depot for a different network

I'm more than happy to do the work to raise this as a "pink" error and add to the PR, but no point if you are determined that multiple networks shouldn't happen.

**Comment by Yousei9** [comment]
I like how you instantly found one of the edge cases I was talking about.

Another pitfall will be having simple integer IDs. They make it impossible for one stop to be part of multiple Networks. Using binary where each bit represents one network, similar to how I encode train composition, could solve that, but it's very prone to user configuration error.

Supporting users messing up their signals already is a nightmare. Adding (binary encoded) network IDs would drive me insane.
So if it works for you locally there's no need to for proper configuration error signaling or enhancing the id handling as I will never push these changes.

**Comment by mgravell** [comment]
I "found" the edge just from thinking about it before starting - it wasn't a "oh, damn" moment. I also thought about bit-wise encoding the networks, but that is probably outside of most users common experience for simple usage, but more importantly connected networks quickly gets *really* complicated - you'd need to use a lot of graph theory to prove whether or not you can lose all your trains via a sequence of steps (since we can only specify the network at stops, not individual trains). IMO disjoint logical networks (that may or may not share a connected physical infrastructure) is fine - but connected networks are a complete non-starter that isn't worth trying to solve.

**Comment by jcreigh** [comment]
Unless I'm not thinking of something, why not reuse the alphabet/number/color signals? That way, a stop could be part of 26 (if you do alphabet) networks simultaneously, which should be more than enough.

You could also do letter + quantity for even more networks, but a stop on A1 wouldn't be able to also be on A2. If someone is using more than 26 subnetworks, they can probably figure out how to deal with it. Supporting users shouldn't be any worse than currently.

And I say it makes sense to give a warning if depots with the same name are on different networks.

It might be possible to lose a train between networks, but it'll fail to path back and the user should notice and be able to deal with it.

Or, if @Yousei9 really doesn't approve of subnetworks still, being able to select trains based on _color_ would be a lot less hacky than train length. That way, if you really want, you can color all the trains on a "subnetwork" the same and select based on that. Of course you can have multiple locomotives, but do it so at least one of them matches.

**Comment by Yousei9** [comment]
@jcreigh 
Generating a dedicated virtual signal for network ID never was the problem.
I'm only going to add features that are well thought out and are useful to all players. Segregation of networks is neither.

Using train and stop colors is an interesting idea but again just throwing in wild ideas will not convince me if only 5min of thinking about implementation make me realize several flaws with the idea.
- Could a user discern FF0000 from FE0000 or does it require fuzzy logic? 
- With fuzzy logic where would the line be drawn and how would you justify the expense of adding said fuzzy logic?
- How to prevent mods automatically coloring from breaking the system?

**Comment by mgravell** [comment]
Colours are already in use due to the lamp.

Alphabet is confusing because it restricts other uses of alphabet and could
cause existing systems to stop working unexpected.

It is moot anyway, I think.

**Comment by jcreigh** [comment]
@Yousei9 My issue is that we have a central storage area that requests as much as it can on one side from a processing area then provides it out on the other side to the larger train network. As far as I can tell, there's no way to prevent it from making a loop by requesting from the output side.

Subnetworks would solve this, tying the output of the processing area to the input of the storage area. But I'm open to obvious suggestions. Or if you really think that sort of system is out of scope for this mod, I guess we'll try to figure something out.

The train colors are set with 0-255 directly for red, green, and blue. User would be able to discern the colors since the values are being displayed right there when setting. Fuzzy wouldn't really be necessary, but you could add signals for minimum red value, maximum red value, etc. It'd be no different than checking for train length. I didn't consider other mods setting the colors automatically, however.

I guess I'll think about it some more.

**Comment by Yousei9** [comment]
LTN's goal is to create direct producer - consumer deliveries on demand.
Sub distribution only moves storage space from one point to another and adds more overhead (trains).

**Pull request closed without merging**
