### PR TITLE
Option to show icons in front of localized names

### PR DESCRIPTION
**Pull request by Quezler**
Currently on one of my server playthroughs we constantly see this to remind us to gather items and such:

Untitled

We can (and have) icon-coded the station names, but whatever its missing is still just text.

This draft adds an option to add the icon of the item/fluid to the left of the mentioned prototype:
Screen Shot 2022-01-05 at 21 34 44
(shown is one message where it is on, then during the next one it was toggled off)

Being able to see icons would make it easier to quickly visually scan through the list in chat vs reading each line.

Putting this in draft mode since there are still other messages left untranslated, not gonna put any more effort into refining this before its greenlit since the concept can still be shot down if you feel like this doesn't belong.

Looking forward to hearing whatever feedback you might have :)

### CODE REVIEW

**Comment by Yousei9** [comment]
Will certainly help with readability. Even with indistinguishable icons it makes it easier to find where item names are.
Reordering strings will break translations. New parts should be just counted up.
Even better alternative is to merge the icon with localname in a lookup table so it becomes a fast NameWithIcon[localname] instead of multiple concats each time.

**Comment by Yousei9** [comment]
3rd middle alternative would be to send a concated string instead of localname:
`if requestStation.no_warnings == false and message_level >= 1 then printmsg({"ltn-message.no-provider-found", to_gps, message_icons and "[img=" .. itype .. "/" .. iname .. "] " .. localname or localname, to_network_id_string}, requestForce, true) end`

**Comment by Quezler** [comment]
when i tried to `..` localname before in an earlier draft factorio complained about it being a table, didn't understand that structure at the time (i'm only a small modder myself) so i went with something i did understand: an extra argument 😅

**Comment by Yousei9** [comment]
Found an even simpler way by replacing localized name with [itype=iname]

**Pull request closed without merging**
