### PR TITLE
1.7.0 zh-CN

### PR DESCRIPTION
**Pull request by 71e6fd52**

### CODE REVIEW

**Comment by Yousei9** [comment]
I was thinking about splitting translations, I can't do myself, into a sub mod so I don't have racing version numbers on the main mod.
What's your take on this idea?

**Comment by 71e6fd52** [comment]
Yes, splitting translations is friendly to developer, but user needs download another mod.
I didn't know if it is right.

There are least three Chinese mod, and I own one.
but I think feedback to upstream like in-game translate is more reasonable.

**Comment by Yousei9** [comment]
It's arguable if having only selected few mods supporting a locale is more user friendly than downloading specific localizations or language packs like Koreans do.

But yes, in the end I mostly want to get rid of maintaining a couple of languages that are way less reliably updated than yours.

**Comment by Yousei9** [comment]
Looks like someone else already made a a chinese language pack including LTN:. https://github.com/aspd199/Factorio-zh-CN-Locale-Library/blob/master/locale/zh-CN/LogisticTrainNetwork_1.6.2.cfg

**Comment by 71e6fd52** [comment]
It looks like just copy, the only difference is that he translates content that I think preserves English better

**Comment by 71e6fd52** [comment]
but I add it to my Chinese mod
https://github.com/71e6fd52/Factorio-Chinese/blob/master/locale/zh-CN/LogisticTrainNetwork.cfg

**Pull request merged**
